### ISSUE TITLE
Essence Problem Models Not Supported

### ISSUE THREAD

**Issue by vincepick** [stacs-cp/AutoIG#3]
Setup python script **setup.py** appears to work correctly: 

`024-10-08 22:43:44: Setting up the tuning: COMPLETED`

However run script, **run.sh** fails: 

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/AutoIG/scripts/collect_results.py", line 197, in <module>
    config, tRs, tRsNoDup = read_data(runDir)
                            ^^^^^^^^^^^^^^^^^
  File "/AutoIG/scripts/collect_results.py", line 47, in read_data
    tRs["score"] = tRs["score"].astype(float)
                   ~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'score'
```

**Comment by vincepick** [comment]
This is no longer applicable, Essence problem models are (partially supported), but there exist more recent issues with better descriptions.

**Comment by vincepick** [comment]
After a full teardown and reimplementation, it is now successfully set up: 

python $AUTOIG/scripts/setup.py --generatorModel $AUTOIG/data/models/simple/generator.essence --problemModel $AUTOIG/data/models/simple/problem.essence --instanceSetting graded --minSolverTime 0 --maxSolverTime 5 --solver chuffed --solverFlags="-f" --maxEvaluations 180 --genSolverTimeLimit 5


<img width="1563" alt="Image" src="https://github.com/user-attachments/assets/276fcf56-92b6-41d4-b290-c3e2aac0d322" />

But unfortunately, run.sh yields the following issue:

+-+-----------+-----------+-----------+---------------+-----------+--------+-----+----+------+
| |   Instance|      Alive|       Best|      Mean best| Exp so far|  W time|  rho|KenW|  Qvar|
+-+-----------+-----------+-----------+---------------+-----------+--------+-----+----+------+
# 2025-03-26 00:22:27 UTC: /AutoIG/scripts/target-runner 1 1 719061008 dummy   -A 137
# 2025-03-26 00:22:30 UTC: DONE (1) Elapsed wall-clock seconds: 2.40
Error! UnboundLocalError: cannot access local variable 'es' where it is not associated with a value
Error: == irace == The output of targetRunner should not be more than two numbers!
== irace == The call to targetRunner was:
/AutoIG/scripts/target-runner 1 1 719061008 dummy   -A 137
== irace == The output was:
Error! UnboundLocalError: cannot access local variable 'es' where it is not associated with a value
== irace == This is not a bug in irace, but means that something failed when running the command(s) above or they were terminated before completion. Try to run the command(s) above from the execution directory '/AutoIG/experiments/simple' to investigate the issue. See also Appendix B (targetRunner troubleshooting checklist) of the User Guide (https://cran.r-project.org/package=irace/vignettes/irace-package.pdf).
In addition: There were 15 warnings (use warnings() to see them)
/AutoIG/experiments/simple/detailed-output /AutoIG/experiments/simple
ls: cannot access 'inst-*.dzn': No such file or directory
/AutoIG/experiments/simple
Traceback (most recent call last):
  File "/AutoIG/scripts/collect_results.py", line 197, in <module>
    config, tRs, tRsNoDup = read_data(runDir)
                            ^^^^^^^^^^^^^^^^^
  File "/AutoIG/scripts/collect_results.py", line 47, in read_data
    tRs["score"] = tRs["score"].astype(float)
                   ~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'score'

**Comment by vincepick** [comment]
In addition, there is another bug with the current implementation of: **get_essence_problem_type** in **essence_pipeline_utils**. 

Will need to discuss this with Oz. 

<img width="1544" alt="Image" src="https://github.com/user-attachments/assets/48f646e8-d747-4237-8a25-a7d008754ec3" />

**Comment by vincepick** [comment]
After quite a bit of debugging, while the previously mentioned point about **get_essence_problem_type** remains an issue, the current implementation is able to generate full runs seemingly correctly. 

Output available at: https://github.com/vincepick/AutoIG/tree/feat/teardown_essence/experiments

**Comment by vincepick** [comment]
As of the most recent pull request to https://github.com/vincepick/AutoIG:Main, it supports generation for models with repair models such as car-sequencing as well.
